# Generated by Django 4.1.1 on 2022-10-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_doctorreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorreg',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
