# Generated by Django 4.1.1 on 2022-10-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_doctorreg_address_alter_doctorreg_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(null=True)),
                ('photo', models.FileField(upload_to='labphotos/')),
                ('doj', models.DateField(auto_now_add=True)),
                ('password', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
