# Generated by Django 4.1.1 on 2022-10-13 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0005_adminlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('test_amount', models.CharField(max_length=500)),
                ('test_details', models.TextField(null=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.laboratory')),
                ('testtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.testtype')),
            ],
        ),
    ]
