# Generated by Django 4.1.1 on 2022-10-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0004_laboratory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='userphotos/')),
                ('proof', models.FileField(upload_to='userphotos/')),
                ('password', models.CharField(max_length=50, unique=True)),
                ('rg_date', models.DateField(auto_now_add=True)),
                ('u_status', models.IntegerField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.place')),
            ],
        ),
    ]
