# Generated by Django 4.1.1 on 2022-10-25 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_userregistration_address'),
        ('Admin', '0005_adminlogin'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('reply', models.TextField(null=True)),
                ('c_status', models.IntegerField(default=0)),
                ('Doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.doctorreg')),
                ('Laboratory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.laboratory')),
                ('User_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.userregistration')),
            ],
        ),
    ]
