# Generated by Django 4.1.1 on 2022-10-25 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_adminlogin'),
        ('Guest', '0002_userregistration_address'),
        ('User', '0002_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('date', models.DateField(auto_now=True)),
                ('Doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.doctorreg')),
                ('Laboratory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin.laboratory')),
                ('User_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.userregistration')),
            ],
        ),
    ]
