# Generated by Django 4.1.2 on 2022-10-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_remove_checkupdetails_appoinment_id_and_more'),
        ('User', '0003_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appoinment',
        ),
    ]
