# Generated by Django 4.1.2 on 2022-10-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_appoinment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appoinment',
        ),
    ]
