# Generated by Django 4.1.2 on 2022-10-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_appoinment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment',
            name='appoinment_time',
        ),
    ]
