# Generated by Django 4.1.1 on 2022-10-15 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0005_adminlogin'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkupdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_details', models.TextField(null=True)),
                ('checkup_result', models.TextField(null=True)),
                ('checkup_status', models.IntegerField(default=0)),
                ('appoinment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.appoinment')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.testtype')),
            ],
        ),
    ]
