# Generated by Django 4.1.2 on 2022-10-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_refer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkupdetails',
            name='appoinment_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='appoinment_id',
        ),
        migrations.RemoveField(
            model_name='refer',
            name='appoinment_id',
        ),
    ]
