# Generated by Django 4.1.2 on 2022-10-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_remove_checkupdetails_appoinment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkupdetails',
            name='test_id',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.RemoveField(
            model_name='refer',
            name='doctor_id',
        ),
        migrations.DeleteModel(
            name='Checkupdetails',
        ),
        migrations.DeleteModel(
            name='refer',
        ),
    ]
