# Generated by Django 4.1.2 on 2022-10-29 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0007_appoinment'),
        ('Laboratory', '0001_initial'),
        ('Doctor', '0008_remove_checkupdetails_test_id_delete_prescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkupdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_details', models.TextField(null=True)),
                ('checkup_result', models.FileField(default=0, upload_to='checkupresult/')),
                ('checkup_status', models.IntegerField(default=0)),
                ('appoinment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.appoinment')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Laboratory.testdetails')),
            ],
        ),
    ]
