# Generated by Django 4.1.2 on 2022-10-29 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_appoinment'),
        ('Doctor', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_medicine', models.TextField(null=True)),
                ('prescription_date', models.DateField(auto_now=True)),
                ('payment_status', models.IntegerField(default=0)),
                ('appoinment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.appoinment')),
            ],
        ),
    ]
