# Generated by Django 4.1.2 on 2022-10-29 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_slots'),
        ('User', '0007_appoinment'),
        ('Doctor', '0010_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='refer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoinment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.appoinment')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.doctorreg')),
            ],
        ),
    ]
